% supply allMouseData generated by loadMouse(suffixList). Enter a pctile to
% find the periods of sustained speed above and below that cutoff

function allMouseData = addSpeedInfo(allMouseData, limLo, limHi, doPlot)
    %% speed stats
    dt = allMouseData(1).dt;
    for mouse=1:numel(allMouseData)
            speed = allMouseData(mouse).speed;
            
            % TODO: compute period of movement with sustained velocity above
            % certain threshold for x seconds. In the following lines, look for
            % above and below 20% of maximal velocity, 10 seconds continuous
            timeInSecs = 2;
            LOWPASSFQ = 1.5;
            [b,a] = butter(2, 2*LOWPASSFQ*dt, 'low');
            speed = filtfilt(b,a,speed);
            
            allMouseData(mouse).hiSpdSustainSegs = sustainedSpeedAbove(speed, limHi, ceil(timeInSecs/dt));
            allMouseData(mouse).loSpdSustainSegs = sustainedSpeedBelow(speed, limLo, ceil(timeInSecs/dt));
    end
end